/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * A document consuming a media file
 */
export type Consumers = {
  /**
   * The unique identifier of the consumer
   */
  id: string;
  /**
   * The nice name of the consumer
   */
  name: string;
  /**
   * The slug of the collection
   */
  collectionSlug: string;
  [k: string]: unknown;
}[];
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    bannerTitle: BannerTitleBlock;
    cmsButton: CMSButtonBlock;
    collectionList: CollectionListBlock;
    emphasizedList: EmphasizedListBlock;
    eventTiles: EventTilesBlock;
    heroSpinner: HeroSpinnerBlock;
    hiddenTitle: HiddenTitleBlock;
    iconList: IconListBlock;
    imageCallout: ImageCalloutBlock;
    metrics: MetricsBlock;
    optimizedImage: OptimizedImageBlock;
    pageTitle: PageTitleBlock;
    relatedCards: RelatedCardsBlock;
    sectionCols: SectionColumnsBlock;
    sectionContent: SectionContentBlock;
    section: SectionBlock;
    sectionTitle: SectionTitleBlock;
  };
  collections: {
    pages: Page;
    subfunds: Subfund;
    events: Event;
    'legal-notices': LegalNotice;
    locations: Location;
    contacts: Contact;
    media: Media;
    documents: Document;
    'hero-images': HeroImage;
    'contact-portraits': ContactPortrait;
    users: User;
    'event-categories': EventCategory;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      relatedEvents: 'events';
    };
    'payload-folders': {
      documentsAndFolders:
        | 'payload-folders'
        | 'pages'
        | 'locations'
        | 'contacts'
        | 'media'
        | 'documents'
        | 'contact-portraits';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    subfunds: SubfundsSelect<false> | SubfundsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'legal-notices': LegalNoticesSelect<false> | LegalNoticesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'hero-images': HeroImagesSelect<false> | HeroImagesSelect<true>;
    'contact-portraits': ContactPortraitsSelect<false> | ContactPortraitsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'event-categories': EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerTitleBlock".
 */
export interface BannerTitleBlock {
  /**
   * The theme is displayed as a pre-title above the main title.
   */
  theme?: string | null;
  /**
   * The title to display.
   */
  title: string;
  /**
   * Banner Title uses Hero Images for greater control over the final result across screen sizes.
   */
  image: string | HeroImage;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bannerTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images".
 */
export interface HeroImage {
  id: string;
  /**
   * If left blank the title will be generated from the file name.
   */
  title?: string | null;
  /**
   * Alt text is important for accessibility and SEO. Describe the image as specifically and briefly as possible.
   */
  alt: string;
  /**
   * Adjust the positioning of the image within its container across breakpoints.
   */
  customPositioning?: {
    smallScreens?: {
      enabled?: boolean | null;
      /**
       * Use left, center, right, or a value in %, em, rem, or px. Defaults to center.
       */
      xPos?: string | null;
      /**
       * Use top, center, bottom, or a value in %, em, rem, or px. Defaults to bottom.
       */
      yPos?: string | null;
    };
    mediumScreens?: {
      enabled?: boolean | null;
      /**
       * Use left, center, right, or a value in %, em, rem, or px. Defaults to center.
       */
      xPos?: string | null;
      /**
       * Use top, center, bottom, or a value in %, em, rem, or px. Defaults to bottom.
       */
      yPos?: string | null;
    };
    largeScreens?: {
      enabled?: boolean | null;
      /**
       * Use left, center, right, or a value in %, em, rem, or px. Defaults to center.
       */
      xPos?: string | null;
      /**
       * Use top, center, bottom, or a value in %, em, rem, or px. Defaults to bottom.
       */
      yPos?: string | null;
    };
  };
  /**
   * Used for image placeholders. Automatically generated from the image.
   */
  blurData?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    optimized?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CMSButtonBlock".
 */
export interface CMSButtonBlock {
  /**
   * Link to a CMS page or collection item. The button will render with an arrow-up-right icon after the label.
   */
  cmsButtonLink: {
    type?: 'reference' | null;
    newTab?: boolean | null;
    allowReferrer?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    label?: string | null;
    /**
     * Choose how the link will be displayed.
     */
    appearance?: 'button' | null;
    styleVariant?: ('flat' | 'outline' | 'ghost') | false;
    colorVariant?: ('default' | 'primary' | 'accent') | false;
    sizeVariant?: ('small' | 'medium' | 'large') | false;
    microInteraction?: ('none' | 'wiggle' | 'upRight') | false;
    iconPosition?: ('none' | 'before' | 'after') | false;
    icon?: string | null;
  };
  analytics?: {
    /**
     * Enabling an Analytics Event will send data to Plausible Analytics when this element is interacted with.
     */
    hasAnalyticsEvent?: boolean | null;
    /**
     * May only contain letters, numbers, spaces, underscores, hyphens, and plus signs. This must match exactly with the Event set up in the Plausible dashboard.
     */
    eventName?: string | null;
    properties?:
      | {
          /**
           * May only contain letters, numbers, underscores, hyphens, and plus signs. This must match exactly with the Property set up in the Plausible dashboard.
           */
          propertyName: string;
          /**
           * May only contain letters, numbers, spaces, underscores, hyphens, and plus signs.
           */
          propertyValue: string;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cmsButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * The title of the page, used for routing, SEO, tabs, and the admin UI.
   */
  title: string;
  layout: {
    /**
     * Select the template for this page. The template value will determine which blocks are available.
     */
    template: 'default' | 'home' | 'navOnly';
    blocks?: (BannerTitleBlock | HeroSpinnerBlock | HiddenTitleBlock | PageTitleBlock | SectionBlock)[] | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  parent?: (string | null) | Page;
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  lastUpdatedAt?: string | null;
  /**
   * Breadcrumbs are generated based on the page hierarchy.
   */
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  template?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSpinnerBlock".
 */
export interface HeroSpinnerBlock {
  /**
   * Time in seconds before automatically transitioning to the next slide.
   */
  slideTimeout: number;
  slides?:
    | {
        backgroundImage: string | HeroImage;
        /**
         * Themes are displayed as a smaller title above the headline.
         */
        theme: string;
        /**
         * The main title of the slide.
         */
        headline: string;
        heroLink: {
          type?: 'reference' | null;
          newTab?: boolean | null;
          allowReferrer?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label?: string | null;
          /**
           * Choose how the link will be displayed.
           */
          appearance?: 'cta' | null;
          styleVariant?: ('flat' | 'outline' | 'ghost') | false;
          colorVariant?: ('default' | 'primary' | 'accent') | false;
          sizeVariant?: ('small' | 'medium' | 'large') | false;
          microInteraction?: ('none' | 'wiggle' | 'upRight') | false;
          iconPosition?: ('none' | 'before' | 'after') | false;
          icon?: string | null;
          analytics?: {
            /**
             * Enabling an Analytics Event will send data to Plausible Analytics when this element is interacted with.
             */
            hasAnalyticsEvent?: boolean | null;
            /**
             * May only contain letters, numbers, spaces, underscores, hyphens, and plus signs. This must match exactly with the Event set up in the Plausible dashboard.
             */
            eventName?: string | null;
            properties?:
              | {
                  /**
                   * May only contain letters, numbers, underscores, hyphens, and plus signs. This must match exactly with the Property set up in the Plausible dashboard.
                   */
                  propertyName: string;
                  /**
                   * May only contain letters, numbers, spaces, underscores, hyphens, and plus signs.
                   */
                  propertyValue: string;
                  id?: string | null;
                }[]
              | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSpinner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HiddenTitleBlock".
 */
export interface HiddenTitleBlock {
  /**
   * A visually hidden title for accessibility purposes. This should only be used if there is no visible title on the page.
   */
  title: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hiddenTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageTitleBlock".
 */
export interface PageTitleBlock {
  title: string;
  /**
   * The subtitle is displayed below the main title in a smaller font size.
   */
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlock".
 */
export interface SectionBlock {
  contentWidth: 'narrow' | 'normal' | 'wide';
  /**
   * Some styles will enforce local dark mode for better contrast.
   */
  backgroundStyle: 'default' | 'azureGradient' | 'azureLight';
  sectionBlocks: (
    | CMSButtonBlock
    | CollectionListBlock
    | EmphasizedListBlock
    | EventTilesBlock
    | IconListBlock
    | ImageCalloutBlock
    | MetricsBlock
    | OptimizedImageBlock
    | RelatedCardsBlock
    | SectionColumnsBlock
    | SectionContentBlock
    | SectionTitleBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionListBlock".
 */
export interface CollectionListBlock {
  /**
   * Select the collection to display in this list.
   */
  listableCollection: 'contacts' | 'events';
  contactFilters?: {
    /**
     * Drag contacts to rearrange their order in the list.
     */
    contacts?: (string | Contact)[] | null;
    /**
     * Choose whether to show portraits in the contact list.
     */
    showPortraits: 'always' | 'never' | 'ifAvailable';
    /**
     * Choose the number of columns for the contact list. The layout will automatically adjust to the screen width.
     */
    columns: '2' | '3';
    squareGrid?: boolean | null;
  };
  eventFilters?: {
    /**
     * Select the display template for the events in the list.
     */
    displayTemplate: 'default' | 'trusteeMeeting';
    /**
     * Select one or more event types to display in the list, leave empty to show all event types.
     */
    types?: ('trusteeMeeting' | 'subfundMeeting' | 'importantDate' | 'njsigEvent' | 'otherEvent')[] | null;
    /**
     * Select one or more attendance options to display in the list, leave empty to show all attendance options.
     */
    attendanceOptions?: ('inPerson' | 'virtual' | 'hybrid')[] | null;
    /**
     * Select one or more event categories to display in the list, leave empty to show all categories.
     */
    categories?: (string | EventCategory)[] | null;
    /**
     * Select the date range for the events to display in the list.
     */
    dateRange: 'all' | 'upcoming' | 'past' | 'custom';
    /**
     * Start date for the custom date range.
     */
    rangeStart?: string | null;
    /**
     * End date for the custom date range. Leave empty to have no end date.
     */
    rangeEnd?: string | null;
    /**
     * Select the sorting order for the events in the list.
     */
    sortBy: 'startDateAsc' | 'startDateDesc';
    /**
     * If enabled, this list will be broken into multiple pages, pagination will be based on the start date of the events.
     */
    pagination?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'collectionList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: string;
  /**
   * Portraits should be square and at least 250x250 pixels. A placeholder will be used if no image is assigned to this contact.
   */
  portrait?: (string | null) | ContactPortrait;
  /**
   * The user type helps differentiate between NJSIG staff, brokers, and trustees.
   */
  type: 'njsig' | 'broker' | 'trustee';
  /**
   * The full name of the contact person.
   */
  name: string;
  /**
   * The contact person's job title.
   */
  title?: string | null;
  /**
   * The organization the contact person is affiliated with.
   */
  organization?: string | null;
  email: string;
  phone?: string | null;
  extension?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-portraits".
 */
export interface ContactPortrait {
  id: string;
  /**
   * The name of the person in the portrait photo.
   */
  name: string;
  /**
   * Used for image placeholders. Automatically generated from the image.
   */
  blurData?: string | null;
  prefix?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'pages';
          value: string | Page;
        }
      | {
          relationTo?: 'locations';
          value: string | Location;
        }
      | {
          relationTo?: 'contacts';
          value: string | Contact;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
      | {
          relationTo?: 'documents';
          value: string | Document;
        }
      | {
          relationTo?: 'contact-portraits';
          value: string | ContactPortrait;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('pages' | 'locations' | 'contacts' | 'media' | 'documents' | 'contact-portraits')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  /**
   * The name of the location.
   */
  name: string;
  streetAddress: string;
  /**
   * Optional second line for street address.
   */
  streetAddress2?: string | null;
  city: string;
  state:
    | 'AL'
    | 'AK'
    | 'AZ'
    | 'AR'
    | 'CA'
    | 'CO'
    | 'CT'
    | 'DE'
    | 'FL'
    | 'GA'
    | 'HI'
    | 'ID'
    | 'IL'
    | 'IN'
    | 'IA'
    | 'KS'
    | 'KY'
    | 'LA'
    | 'ME'
    | 'MD'
    | 'MA'
    | 'MI'
    | 'MN'
    | 'MS'
    | 'MO'
    | 'MT'
    | 'NE'
    | 'NV'
    | 'NH'
    | 'NJ'
    | 'NM'
    | 'NY'
    | 'NC'
    | 'ND'
    | 'OH'
    | 'OK'
    | 'OR'
    | 'PA'
    | 'RI'
    | 'SC'
    | 'SD'
    | 'TN'
    | 'TX'
    | 'UT'
    | 'VT'
    | 'VA'
    | 'WA'
    | 'WV'
    | 'WI'
    | 'WY';
  zipCode: string;
  phone?: string | null;
  website?: {
    type?: 'custom' | null;
    newTab?: boolean | null;
    allowReferrer?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    label?: string | null;
  };
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * If left blank the title will be generated from the file name.
   */
  title?: string | null;
  /**
   * Alt text is important for accessibility and SEO. Describe the image as specifically and briefly as possible.
   */
  alt: string;
  /**
   * Captions may or may not be displayed depending on where an image is used.
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Used for image placeholders. Automatically generated from the image.
   */
  blurData?: string | null;
  relatedEvents?: {
    docs?: (string | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  prefix?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Select the type of event. Important Date is used for non-event dates like the renewal deadline.
   */
  eventType: 'trusteeMeeting' | 'subfundMeeting' | 'importantDate' | 'njsigEvent' | 'otherEvent';
  /**
   * The title of the page, used for routing, SEO, tabs, and the admin UI.
   */
  title: string;
  /**
   * Formatting options are limited to maintain consistency across the site.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Persons or organizations presenting the main topic
   */
  presenters?:
    | {
        name: string;
        /**
         * Title or Affiliation
         */
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * QPA or other credits
   */
  credits?:
    | {
        credit: string;
        id?: string | null;
      }[]
    | null;
  startDate: string;
  endDate?: string | null;
  registrationTime?: string | null;
  startTime: string;
  endTime?: string | null;
  /**
   * Select all the categories that apply to this event.
   */
  categories: (string | EventCategory)[];
  /**
   * The contact person for the event.
   */
  contact?: (string | null) | Contact;
  attendanceOptions: 'inPerson' | 'virtual' | 'hybrid';
  virtualProvider?: ('zoom' | 'googleMeet' | 'microsoftTeams' | 'goToMeeting' | 'other') | null;
  /**
   * The link to the virtual event. If no link is provided, it will be displayed as "TBA" on the event page.
   */
  virtualLink?: string | null;
  virtualPasscode?: string | null;
  /**
   * If no location is selected it will be displayed as "TBA" on the event page.
   */
  location?: (string | null) | Location;
  /**
   * The meeting agenda file provided here will be displayed on the event page and the legal notices page.
   */
  trusteeMeetingAgenda?: {
    resource: {
      type: 'document';
      /**
       * The resource icon should be as closely related to the resource as possible.
       */
      icon?: string | null;
      /**
       * Select or upload a document.
       */
      document?: (string | null) | Document;
      /**
       * Select or upload a video or audio clip.
       */
      audioVideo?: (string | null) | Media;
      /**
       * Provide a URL to an external resource or a reference to a CMS item.
       */
      link?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        allowReferrer?: boolean | null;
        reference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        url?: string | null;
        label?: string | null;
      };
    };
  };
  /**
   * The meeting minutes summary and file provided here will be displayed on the event page and the legal notices page.
   */
  trusteeMeetingMinutes?: {
    /**
     * A brief summary of the trustee meeting minutes (optional).
     */
    minutesSummary?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    resource: {
      type: 'document';
      /**
       * The resource icon should be as closely related to the resource as possible.
       */
      icon?: string | null;
      /**
       * Select or upload a document.
       */
      document?: (string | null) | Document;
      /**
       * Select or upload a video or audio clip.
       */
      audioVideo?: (string | null) | Media;
      /**
       * Provide a URL to an external resource or a reference to a CMS item.
       */
      link?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        allowReferrer?: boolean | null;
        reference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        url?: string | null;
        label?: string | null;
      };
    };
  };
  resources?:
    | {
        resource: {
          type: 'document' | 'audioVideo' | 'link';
          /**
           * The resource icon should be as closely related to the resource as possible.
           */
          icon?: string | null;
          /**
           * Select or upload a document.
           */
          document?: (string | null) | Document;
          /**
           * Select or upload a video or audio clip.
           */
          audioVideo?: (string | null) | Media;
          /**
           * Provide a URL to an external resource or a reference to a CMS item.
           */
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            allowReferrer?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label?: string | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Mark this event as important to emphasize its significance.
   */
  important?: boolean | null;
  /**
   * Event slugs are not unique, as even URLs include the event date.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  lastUpdatedAt?: string | null;
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories".
 */
export interface EventCategory {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * If left blank the title will be generated from the file name.
   */
  title?: string | null;
  consumers?: Consumers;
  fileType?: string | null;
  publishedAt?: string | null;
  lastUpdatedAt?: string | null;
  prefix?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmphasizedListBlock".
 */
export interface EmphasizedListBlock {
  /**
   * Select the color of the triangular bullets
   */
  bullColor?: ('primary' | 'accent') | null;
  listItems?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'emphasizedList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventTilesBlock".
 */
export interface EventTilesBlock {
  /**
   * Set the number of tiles to display, including the "View All" tile
   */
  tiles: number;
  /**
   * Select categories to filter events by. Leave empty to show all events. NJSIG events flagged as "Important" will always be shown.
   */
  categoryFilters?: (string | EventCategory)[] | null;
  /**
   * Toggle to show or hide the "View All" tile at the end of the list.
   */
  showViewAll?: boolean | null;
  /**
   * Enable the "Subscribe" tile when there are no events to display. NOTE: The subscribe functionality is still under development.
   */
  enableSubscribe?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventTiles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconListBlock".
 */
export interface IconListBlock {
  /**
   * A two column layout will display odd items in the left column and even items in the right column. Two columns will stack as one column on smaller screens.
   */
  columns?: ('one' | 'two') | null;
  items?:
    | {
        icon: string;
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCalloutBlock".
 */
export interface ImageCalloutBlock {
  calloutContent: {
    /**
     * The theme is displayed as a title above the callout text.
     */
    theme?: string | null;
    /**
     * The content to display in the callout.
     */
    content: string;
    position: 'left' | 'right';
  };
  calloutImage: {
    /**
     * You may specify a height and/or width to force a specific image size. Only set one or the other to maintain the image aspect ratio.
     */
    image: string | Media;
    border: 'none' | 'primaryMidtone';
    width?: number | null;
    height?: number | null;
    /**
     * Enabling this option will prioritize the loading of this image. This should only be used for "above the fold" images.
     */
    priority?: boolean | null;
    /**
     * Enabling this option will display a low-quality blurred image placeholder while the full image loads.
     */
    placeholder?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageCallout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  /**
   * The number of columns to display. On smaller screens, the layout will adjust to fit the screen size.
   */
  columns?: ('one' | 'two' | 'three' | 'four') | null;
  items?:
    | {
        icon: string;
        /**
         * The background color for the icon.
         */
        iconBackgroundColor:
          | 'azureMidtone'
          | 'ceruleanMidtone'
          | 'glacialMidtone'
          | 'raspberryMidtone'
          | 'seaGreenMidtone'
          | 'sushiMidtone'
          | 'tahitiGoldMidtone'
          | 'trendyPinkMidtone';
        /**
         * The numeric metric value to display.
         */
        value: number;
        /**
         * The label to display below the metric value.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OptimizedImageBlock".
 */
export interface OptimizedImageBlock {
  /**
   * You may specify a height and/or width to force a specific image size. Only set one or the other to maintain the image aspect ratio.
   */
  image: string | Media;
  width?: number | null;
  height?: number | null;
  /**
   * Enabling this option will add automatic margins to center the image within its container.
   */
  centerImage?: boolean | null;
  /**
   * Enabling this option will prioritize the loading of this image. This should only be used for "above the fold" images.
   */
  priority?: boolean | null;
  /**
   * Enabling this option will display a low-quality blurred image placeholder while the full image loads.
   */
  placeholder?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'optimizedImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedCardsBlock".
 */
export interface RelatedCardsBlock {
  cards?:
    | {
        title: string;
        description: string;
        link: {
          type?: 'reference' | null;
          newTab?: boolean | null;
          allowReferrer?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionColumnsBlock".
 */
export interface SectionColumnsBlock {
  /**
   * Columns will take the full width of the page when stacked on small screens.
   */
  widths: 'thirty-seventy' | 'forty-sixty' | 'fifty-fifty' | 'sixty-forty' | 'seventy-thirty';
  /**
   * Columns will stack on the selected breakpoint and smaller.
   */
  stackAt: 'mobile' | 'tablet' | 'desktop';
  /**
   * This setting determines how columns with different heights are aligned vertically.
   */
  vertAlign: 'top' | 'center' | 'bottom';
  colOne: {
    visibility: 'desktop' | 'tablet' | 'mobile';
    colBlocks?:
      | (
          | CMSButtonBlock
          | CollectionListBlock
          | EmphasizedListBlock
          | ImageCalloutBlock
          | OptimizedImageBlock
          | SectionContentBlock
          | SectionTitleBlock
        )[]
      | null;
  };
  colTwo: {
    visibility: 'desktop' | 'tablet' | 'mobile';
    colBlocks?:
      | (
          | CMSButtonBlock
          | CollectionListBlock
          | EmphasizedListBlock
          | ImageCalloutBlock
          | OptimizedImageBlock
          | SectionContentBlock
          | SectionTitleBlock
        )[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionCols';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionContentBlock".
 */
export interface SectionContentBlock {
  /**
   * If enabled, the content will be centered within the section.
   */
  centerBlock?: boolean | null;
  /**
   * Formatting options are limited to maintain consistency across the site.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTitleBlock".
 */
export interface SectionTitleBlock {
  /**
   * The theme is displayed as a pre-title above the main title.
   */
  theme: string;
  /**
   * The main title of the section.
   */
  title: string;
  /**
   * You can choose to visually hide the theme or title.
   */
  viewOptions: 'titleAndTheme' | 'titleOnly' | 'themeOnly';
  /**
   * Include a 40px bottom margin for the section title.
   */
  bottomMargin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subfunds".
 */
export interface Subfund {
  id: string;
  /**
   * The theme applies a color scheme to all themeable elements on the page.
   */
  theme: 'bacceic' | 'caip' | 'ericnorth' | 'ericsouth' | 'ericwest' | 'mocssif' | 'njeif';
  /**
   * The full name of the sub-fund, used for SEO.
   */
  name: string;
  /**
   * The short name of the sub-fund, used for routing, display, and the admin UI.
   */
  shortName: string;
  content: {
    /**
     * A summary of the sub-fund, used for SEO and display. The summary should include the full name, counties, year founded, and administrator.
     */
    summary: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    administrators: (string | Contact)[];
    reps: (string | Contact)[];
    /**
     * Select event categories to filter events related to this sub-fund. If no categories are selected, all events will be shown.
     */
    eventFilters: (string | EventCategory)[];
    /**
     * Select event categories to filter past meetings related to this sub-fund. If no categories are selected, the past meetings section will be hidden.
     */
    pastMeetingsFilters: (string | EventCategory)[];
    resources?:
      | {
          resource: {
            type: 'document' | 'audioVideo' | 'link';
            /**
             * The resource icon should be as closely related to the resource as possible.
             */
            icon?: string | null;
            /**
             * Select or upload a document.
             */
            document?: (string | null) | Document;
            /**
             * Select or upload a video or audio clip.
             */
            audioVideo?: (string | null) | Media;
            /**
             * Provide a URL to an external resource or a reference to a CMS item.
             */
            link?: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              allowReferrer?: boolean | null;
              reference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              url?: string | null;
              label?: string | null;
            };
          };
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notices".
 */
export interface LegalNotice {
  id: string;
  /**
   * The type of legal notice will determine how it is displayed.
   */
  noticeType: 'legalNotice' | 'rfp' | 'rfpAward';
  /**
   * The title of the legal notice.
   */
  title: string;
  /**
   * Formatting options are limited to maintain consistency across the site.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The date the legal notice is posted. Future dates will not be visible to the public until the posting date is reached.
   */
  postingDate: string;
  /**
   * RFPs will be marked as closed on this date.
   */
  closeDate?: string | null;
  /**
   * Tracking ID for RFPs. e.g. "NJSIG-2024-001"
   */
  rfpTracking?: string | null;
  /**
   * Attach files related to this legal notice, such as RFP documents or award details.
   */
  resources?:
    | {
        resource: {
          type: 'document';
          /**
           * The resource icon should be as closely related to the resource as possible.
           */
          icon?: string | null;
          /**
           * Select or upload a document.
           */
          document?: (string | null) | Document;
          /**
           * Select or upload a video or audio clip.
           */
          audioVideo?: (string | null) | Media;
          /**
           * Provide a URL to an external resource or a reference to a CMS item.
           */
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            allowReferrer?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label?: string | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Mark this legal notice as important to emphasize its significance.
   */
  important?: boolean | null;
  publishedAt?: string | null;
  lastUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'subfunds';
        value: string | Subfund;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'legal-notices';
        value: string | LegalNotice;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'contacts';
        value: string | Contact;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'hero-images';
        value: string | HeroImage;
      } | null)
    | ({
        relationTo: 'contact-portraits';
        value: string | ContactPortrait;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'event-categories';
        value: string | EventCategory;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        template?: T;
        blocks?: T | {};
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  parent?: T;
  slug?: T;
  slugLock?: T;
  publishedAt?: T;
  lastUpdatedAt?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  template?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subfunds_select".
 */
export interface SubfundsSelect<T extends boolean = true> {
  theme?: T;
  name?: T;
  shortName?: T;
  content?:
    | T
    | {
        summary?: T;
        administrators?: T;
        reps?: T;
        eventFilters?: T;
        pastMeetingsFilters?: T;
        resources?:
          | T
          | {
              resource?:
                | T
                | {
                    type?: T;
                    icon?: T;
                    document?: T;
                    audioVideo?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          allowReferrer?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                  };
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  eventType?: T;
  title?: T;
  description?: T;
  presenters?:
    | T
    | {
        name?: T;
        title?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        credit?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  registrationTime?: T;
  startTime?: T;
  endTime?: T;
  categories?: T;
  contact?: T;
  attendanceOptions?: T;
  virtualProvider?: T;
  virtualLink?: T;
  virtualPasscode?: T;
  location?: T;
  trusteeMeetingAgenda?:
    | T
    | {
        resource?:
          | T
          | {
              type?: T;
              icon?: T;
              document?: T;
              audioVideo?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
      };
  trusteeMeetingMinutes?:
    | T
    | {
        minutesSummary?: T;
        resource?:
          | T
          | {
              type?: T;
              icon?: T;
              document?: T;
              audioVideo?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
      };
  resources?:
    | T
    | {
        resource?:
          | T
          | {
              type?: T;
              icon?: T;
              document?: T;
              audioVideo?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        id?: T;
      };
  important?: T;
  slug?: T;
  slugLock?: T;
  publishedAt?: T;
  lastUpdatedAt?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notices_select".
 */
export interface LegalNoticesSelect<T extends boolean = true> {
  noticeType?: T;
  title?: T;
  content?: T;
  postingDate?: T;
  closeDate?: T;
  rfpTracking?: T;
  resources?:
    | T
    | {
        resource?:
          | T
          | {
              type?: T;
              icon?: T;
              document?: T;
              audioVideo?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        id?: T;
      };
  important?: T;
  publishedAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  streetAddress?: T;
  streetAddress2?: T;
  city?: T;
  state?: T;
  zipCode?: T;
  phone?: T;
  website?:
    | T
    | {
        type?: T;
        newTab?: T;
        allowReferrer?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  portrait?: T;
  type?: T;
  name?: T;
  title?: T;
  organization?: T;
  email?: T;
  phone?: T;
  extension?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  blurData?: T;
  relatedEvents?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  consumers?: T;
  fileType?: T;
  publishedAt?: T;
  lastUpdatedAt?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images_select".
 */
export interface HeroImagesSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  customPositioning?:
    | T
    | {
        smallScreens?:
          | T
          | {
              enabled?: T;
              xPos?: T;
              yPos?: T;
            };
        mediumScreens?:
          | T
          | {
              enabled?: T;
              xPos?: T;
              yPos?: T;
            };
        largeScreens?:
          | T
          | {
              enabled?: T;
              xPos?: T;
              yPos?: T;
            };
      };
  blurData?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        optimized?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xs?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-portraits_select".
 */
export interface ContactPortraitsSelect<T extends boolean = true> {
  name?: T;
  blurData?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navGroups?:
    | {
        /**
         * Group label for the navigation links, will be displayed as the button text in the header.
         */
        label: string;
        /**
         * Callouts occupy the first column of a navigation group, they display descriptive copy and a call to action.
         */
        callout: {
          title: string;
          text: string;
          calloutLink: {
            type?: 'reference' | null;
            newTab?: boolean | null;
            allowReferrer?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label?: string | null;
          };
        };
        /**
         * Links are shown in two columns on desktop. On mobile the columns stack vertically.
         */
        links?: {
          colOne?:
            | {
                link: {
                  type?: 'reference' | null;
                  newTab?: boolean | null;
                  allowReferrer?: boolean | null;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  url?: string | null;
                  label?: string | null;
                  linkIcon?: string | null;
                  /**
                   * The primary link text should be a page title or concise label.
                   */
                  linkTitle: string;
                  /**
                   * The secondary link text should be a short description of the link.
                   */
                  linkDescription?: string | null;
                };
                id?: string | null;
              }[]
            | null;
          colTwo?:
            | {
                link: {
                  type?: 'reference' | null;
                  newTab?: boolean | null;
                  allowReferrer?: boolean | null;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  url?: string | null;
                  label?: string | null;
                  linkIcon?: string | null;
                  /**
                   * The primary link text should be a page title or concise label.
                   */
                  linkTitle: string;
                  /**
                   * The secondary link text should be a short description of the link.
                   */
                  linkDescription?: string | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        link: {
          type?: 'reference' | null;
          newTab?: boolean | null;
          allowReferrer?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label?: string | null;
          /**
           * Choose how the link will be displayed.
           */
          appearance?: 'cta' | null;
          styleVariant?: ('flat' | 'outline' | 'ghost') | false;
          colorVariant?: ('default' | 'primary' | 'accent') | false;
          sizeVariant?: ('small' | 'medium' | 'large') | false;
          microInteraction?: ('none' | 'wiggle' | 'upRight') | false;
          iconPosition?: ('none' | 'before' | 'after') | false;
          icon?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Add up to 6 navigation groups for the footer.
   */
  navGroups?:
    | {
        label: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                allowReferrer?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add links to privacy policy, terms of use, etc.
   */
  policyLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          allowReferrer?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navGroups?:
    | T
    | {
        label?: T;
        callout?:
          | T
          | {
              title?: T;
              text?: T;
              calloutLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        links?:
          | T
          | {
              colOne?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          allowReferrer?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          linkIcon?: T;
                          linkTitle?: T;
                          linkDescription?: T;
                        };
                    id?: T;
                  };
              colTwo?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          allowReferrer?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          linkIcon?: T;
                          linkTitle?: T;
                          linkDescription?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              allowReferrer?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              styleVariant?: T;
              colorVariant?: T;
              sizeVariant?: T;
              microInteraction?: T;
              iconPosition?: T;
              icon?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    allowReferrer?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  policyLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              allowReferrer?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'subfunds';
          value: string | Subfund;
        } | null)
      | ({
          relationTo: 'events';
          value: string | Event;
        } | null)
      | ({
          relationTo: 'legal-notices';
          value: string | LegalNotice;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}