on:
  pull_request:
    branches:
      - preview
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: Linting & Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    # Bail out on draft pull requests
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Next Linting
        run: pnpm lint:next

      - name: Type Checking
        run: pnpm lint:types
