name: pr-title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

permissions:
  pull-requests: write

jobs:
  main:
    name: lint-pr-title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            chore
            docs
            revert
            test
          scopes: |
            deps
            util
            component
            global
            field
            block
            collection
            page
            api
            config
          # Disallow uppercase letters at the beginning of the subject
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            doesn't match the configured pattern. Please ensure the subject
            doesn't start with an uppercase letter.
      - uses: marocchino/sticky-pull-request-comment@v3
          # When the previous step fails, the workflow would stop. By adding this
          # condition the execution can continue with the populated error message.continue-on-error:
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pre-title-lint-error
          message: |
            Pull Request titles must follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format.

            ${{ steps.lint_pr_title.outputs.error_message }}

            ```
            feat(ui): add Button component
            ^    ^    ^
            |    |    |__ Subject
            |    |_______ Scope
            |____________ Type
            ```
      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          header: pre-title-lint-error
          delete: true
